### ISSUE TITLE
homework-practice-03 HuberRegressor

### ISSUE THREAD

**Issue by Kurt212** [esokolov/ml-course-hse#68]
Когда сдаю файл с HuberRegressor в яндекс контест чекер выдает следующее:
```
test_2_predict (__main__.Test) ... ERROR
test_3_calc_loss (__main__.Test) ... ERROR
test_4_calc_gradient (__main__.Test) ... ERROR

======================================================================
ERROR: test_2_predict (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tester.py", line 33, in test_2_predict
    hr = got.HuberReg(delta=1.0, gd_type='full',
AttributeError: 'module' object has no attribute 'HuberReg'

======================================================================
ERROR: test_3_calc_loss (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tester.py", line 60, in test_3_calc_loss
    hr = got.HuberReg(delta=1.0, gd_type='full',
AttributeError: 'module' object has no attribute 'HuberReg'

======================================================================
ERROR: test_4_calc_gradient (__main__.Test)
-------------------------

File is too long to be displayed fully
```
Что с этим делать?

**Comment by new-okaerinasai** [comment]
Перезашлите с названием класса HuberReg. Прототип на гитхабе я обновил.

**Comment by new-okaerinasai** [comment]
Да, действительно. Не договорились о шаблонах. Я снова обновил задание.
